CREATE TABLE `country_timezones`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `country_id` BIGINT NOT NULL,
    `timezone_id` BIGINT NOT NULL
);

CREATE TABLE `relation`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `first_country` BIGINT NOT NULL,
    `second_country` BIGINT NOT NULL,
    `free_entry` TINYINT(1) NOT NULL,
    `possibility_to_stay_forever` TINYINT(1) NOT NULL
);

CREATE TABLE `timezone`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `zone` SMALLINT NOT NULL
);

CREATE TABLE `country`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `language` VARCHAR(255) NOT NULL,
    `continent` VARCHAR(255) NOT NULL
);

CREATE TABLE `road`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `first_country` BIGINT NOT NULL,
    `second_country` BIGINT NOT NULL,
    `transport` VARCHAR(255) NOT NULL,
    `time_hours` BIGINT NOT NULL
);

CREATE TABLE `tags`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL
);

CREATE TABLE `country_tags`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `country_id` BIGINT UNSIGNED NOT NULL,
    `tag_id` BIGINT UNSIGNED NOT NULL
);

